### ISSUE TITLE
[BUG] Improvements on MemmapTensor

### ISSUE THREAD

**Issue by vmoens** [pytorch-labs/tensordict#194]
## Describe the bug

We need to do some woodwork on MemmapTensor:
- [ ] Remove the ownership and replace it by a check over the number of times the array is being opened (for temporary files only)
- [ ] Solve a bug where calling `MemmapTensor(memmap_tensor[idx])` returns the wrong view of the `MemmapTensor` #193 
- [ ] Improve `MemmapTensor` creation args, including: creating a `Memmap` on a specific location (#189)
- [ ] Improve the way we copy a `Memmap` from one place to another, if we want and if we don't want to change the filename

cc @tcbegley

**Comment by tcbegley** [comment]
- [ ] `AttributeError` on `Tensor` attributes when creating one `MemmapTensor` from another. (#192 <- needs to be adapted to recently merged #193)

I'll also update #189, though the desired no-op behaviour there is blocked by #192.
